#!/usr/bin/env python3
MINUTES_IN_DAY = 60 * 24


def minutesToTime(minutes: int) -> str:
    h = minutes // 60
    m = minutes % 60
    return f"{h:0>2}:{m:0>2}"


print("[", end="")
for i in range(0, MINUTES_IN_DAY):
    print("[{}, {}]".format(minutesToTime(i), minutesToTime(i + 1)), end="")
    if i != MINUTES_IN_DAY - 1:
        print(", ", end="")
print("]", end="")
print()
print("[00:00, 24:00]")
print(1)
